### PR TITLE
Do not use prefix for default language.

### PR DESCRIPTION
**Pull request by alexantr**
If language restoring and showing default language are disabled we don't need in prefix for default language.

### CODE REVIEW

**Comment by mikehaertl** [comment]
I had not time yet to look closer at this. To make it easier: Could you maybe give us an example which URLs you call in order and what is the outcome with/without your change?

**Comment by alexantr** [comment]
For example, we have settings:
```php
[
    'sourceLanguage' => 'en-US',
    'language' => 'en-US',
    // ...
    'components' => [
        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'enablePrettyUrl' => true,
            'enableLanguageDetection' => false,
            'enableLanguagePersistence' => false,
            'enableStrictParsing' => true,
            'suffix' => '/',
            'languages' => ['en' => 'en-US', 'ru' => 'ru-RU'],
            'rules' => [
                ['pattern' => '', 'route' => 'site/index'],
                ['pattern' => '<controller:[0-9a-z-]+>/<action:[0-9a-z-]+>', 'route' => '<controller>/<action>'],
            ],
        ],
        // ...
    ],
    // ...
];
```
**Note:** ```enableLanguageDetection``` and ```enableLanguagePersistence``` are disabled.

And with this config we have pages without default language in URLs:
http://example.com/
http://example.com/ru/
http://example.com/site/about/
http://example.com/ru/site/about/

**What problem?**

Problem with links to pages with default language:
```Url::to(['site/index', 'language' => 'en-US']);``` outputs **/en/** instead **/**
```Url::to(['site/about', 'language' => 'en-US']);``` outputs **/en/site/about/** instead **/site/about/**

This links with prefix **/en/** always redirect to pages without prefix **/en/**.

With this fix ```createUrl()``` generates links without default language prefix.
With disabled ```enableLanguagePersistence``` we don't need in "reset" URLs.

**Comment by mikehaertl** [comment]
Ok, this seems to make sense. I'll merge this and try to add a test case for it. Then there will be a new release soon.

Thanks!

**Comment by mikehaertl** [comment]
@alexantr You forgot to test for `!$this->enableLanguageDetection`. I think we should add it. Agree?

**Comment by alexantr** [comment]
I see **enableLanguageDetection*** uses only when ```$language === null```.
New code triggers only when language is not null, because uses test ```$language === $this->getDefaultLanguage()```
Maybe we should add it to prevent bugs in future.

**Comment by mikehaertl** [comment]
@alexantr I think you mixed things up here: The test for `$language===null` is in `processLocaleUrl()` (for parsing), while we're in `createUrl()` here. ;)

Anyway, I'll add it.

**Comment by alexantr** [comment]
:+1:
Thanks for new release.

**Comment by infoitservit** [comment]
Sorry to reopen this...I'm facing the same problem that generates this issue.
I'm trying to create rel="alternate" tag for google to distinguish between default language (en) and the others.
I'm using, on any page, the function Url::current(['language' => 'xx', true]) to generate any variation of the current url for each language available (xx is en, it, ru etc...)
It works well for any language but, when i try to generate default url with en language, it always generates a url with the "/en/" parameter.
There is an "automatic" way to avoid this? Configuration I'm using:
`'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['en', 'it' => 'it-IT'],
            'enableLanguageDetection' => true,
            'enableDefaultLanguageUrlCode' => false,
            'enableLanguagePersistence' => true,
            'keepUppercaseLanguageCode' => true,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,`

Thanks!

**Comment by mikehaertl** [comment]
@infoitservit This is expected because of the "reset case". See here: https://github.com/codemix/yii2-localeurls#reset-to-default-language

I've committed a little change, so that you can pass an empty `language` parameter, which will give you the URL in the default language without language:

```
<?= Url::to(['site/page', 'language' => '']) ?>
```

I've also added a test for this. But to make sure, can you help test this? I've pushed the change to master.

**Comment by mikehaertl** [comment]
@infoitservit I've released 1.4.6 that includes the mentioned changes. There's also a note in the README now.

**Comment by infoitservit** [comment]
Oh, thank you @mikehaertl ! Had no time to test by the way...is it tested?

**Comment by mikehaertl** [comment]
@infoitservit Our test cases are pretty extensive as we try to catch almost any thinkable setup. The test for the new features succeeds, so I'm quite confident that it works as expected.

But still interested to get results from a real world test. So please let me know after you tried if it solves the problem for you.

**Comment by infoitservit** [comment]
Ok @mikehaertl , thanks! I'll let you know!

**Comment by infoitservit** [comment]
Just tested out, seems it works great! Thank you!

**Pull request merged**
