### PR TITLE
Fix error on redirect to //

### PR DESCRIPTION
**Pull request by macklus**
Not sure why, but when i load http://domain.ltd or http://domain.ltd/, it redirects to /es/site/index, instead of http://domain.ltd/es/site/index

Trace log: [trace][codemix\localeurls\UrlManager::redirectToLanguage] Redirecting to //es/site/index.

PR fix that problem cleaning url if it starts on //

### CODE REVIEW

**Comment by mikehaertl** [comment]
Sorry, I don't get the problem. None of your URLs start with `//`. So what exactly is this fixing?

**Comment by macklus** [comment]
Problem is that, sometimes, your plugin try to redirect to //langcode/controller/action instead of /langcode/controller/action.

No sure why this problem appears (maybe because i use nginx?), but only way i can solve it is with PR i attach

basically, if url start with //, it change it to /

**Comment by mikehaertl** [comment]
I will try to reproduce the issue. I've not seen it before.

**Comment by macklus** [comment]
More test done. If i use https://github.com/dektrium/yii2-user module, generate URLs has same problem. Current config are:

```
'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['es', 'en' => 'us', 'fr', 'de'],
            'enableDefaultLanguageUrlCode' => true,
            'enableLanguagePersistence' => true,
            'enableLanguageDetection' => false,
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'ignoreLanguageUrlPatterns' => [
                //'#^site/(login|register)#' => '#^(login|register)#',
                '#^assets/#' => '#^assets/#',
                '#^img/#' => '#^img/#',
                '#^api/#' => '#^api/#',
            ],
            'rules' => [],
        ],
```

so far i see, dektrium problem seems to be on createUrl function.

hope it heelps

**Comment by macklus** [comment]
Looking deeper on codemix failure, i fix that on createUrl function:

```
diff --git a/UrlManager.php b/UrlManager.php
index 57f6306..6f6b5df 100644
--- a/UrlManager.php
+++ b/UrlManager.php
@@ -247,7 +247,12 @@ class UrlManager extends BaseUrlManager
                     }
                 }
                 $needleLength = strlen($needle);
-                return $needleLength ? substr_replace($url, "$needle/$language", 0, $needleLength) : "/$language$url";
+                $cleanUrl = $needleLength ? substr_replace($url, "$needle/$language", 0, $needleLength) : "/$language$url";
+                if (substr($cleanUrl, 0, 2) == '//') {
+                    Yii::trace("Cleaning...", __METHOD__);
+                    $cleanUrl = str_replace("//", "/", $cleanUrl);
+                }
+                return $cleanUrl;
             }
         } else {
             return parent::createUrl($params);
```

Same problem (url starts with // )

**Comment by mikehaertl** [comment]
@macklus If it also happens with other extensions, it indicates that the problem is somewhere in your setup. I'm closing this for now.

If you still think it's something that we need to fix here, please provide a full (simplified) example how to reproduce the issue. Or even create a test case. You can check the existing test cases which already cover many different configurations. None of them had an issue with double slashes so far.

**Pull request closed without merging**
