### PR TITLE
Fix problems with double slashes.

### PR DESCRIPTION
**Pull request by smilemd**
This PR will fix redirect for home URLs and Url::to problem.

### CODE REVIEW

**Comment by smilemd** [comment]
by the way, this part is not required any more.

```
// Required to prevent double slashes on generated URLs
if ($this->suffix==='/' && $route==='') {
        $url = rtrim($url, '/').'/';
}
```

**Comment by mikehaertl** [comment]
Yeah, I had the same solution in mind. My problem with this is, that I really want to nail it down: Only do this replacement, when we create a root URL. There may be conditions when a URL really contains `//` - and we don't want to bother with that. That's why I'm not really happy with that fix.

**Comment by smilemd** [comment]
how about to check just the start and end of string?
```
 $url = preg_replace('#^//$#', '/', $url);
```

**Comment by mikehaertl** [comment]
Double slashes could also appear in the middle.

See, this is really tricky. The main problem is really, that you want to use `/` instead of `site/index`. Is this really such a hard requirement?

**Pull request closed without merging**
