### PR TITLE
Fix code examples

### PR DESCRIPTION
**Pull request by ufocoder**

### CODE REVIEW

**Comment by mikehaertl** [comment]
Thanks!

**Comment by mikehaertl** [comment]
@ufocoder Sorry, i misread your changes. The trailing `,` are correct and even considered good practice in PHP, so I will undo your changes.

**Comment by ufocoder** [comment]
O'key. But in any case there's no comma after language option in component configuration

**Comment by mikehaertl** [comment]
yup, thanks. i've fixed that now.

**Pull request merged**
