### PR TITLE
Fix problems with double slashes.

### PR DESCRIPTION
**Pull request by smilemd**
This PR will fix redirect for home URLs and Url::to problem.

### CODE REVIEW

**Comment by mikehaertl** [comment]
Sorry, this fix is incomplete and also isn't based on the latest code. It breaks some of the unit tests, so it does not work for all situations.

**Comment by smilemd** [comment]
yeah, i saw :( looking for another solution

**Comment by mikehaertl** [comment]
@smilemd You should try to get the unit tests running locally. It's actually pretty easy. All you should need is to run `phpunit` from the project home directory.

**Comment by smilemd** [comment]
ok, i'll try. tnx

**Pull request closed without merging**
