### PR TITLE
Decode redirect URL

### PR DESCRIPTION
**Pull request by panchenkodv**
Workaround for decode URL in redirect function.

### CODE REVIEW

**Comment by mikehaertl** [comment]
This is a very specific use case and I'm not convinced yet, that we need an extra config option for that. Maybe we can find a better way.

**Comment by panchenkodv** [comment]
I try explain in issue what a problem I have occurred.

> Open /en/some/slug/url redirects to /some%2Fslug%2Furl which gives a 404 from the webserver due to the %2F in the URL

It is real problem. However, not all users need to decode the URL, that why it is made by extra config option in order to not break anything on anyone who already works as works. Who no need this option -- fine, it is default false and all fine. Who need -- set it into 'true' and enjoy correct redirecting.

**Comment by mikehaertl** [comment]
I understand your problem. But it's caused by URLs that don't come from Yii. This is a very seldom and special case and I'm not conviced that we should support this case. I don't want to add config options if they are hardly ever used except in unusual cases like yours. Each options requires special care, when we extend the extension with new features. I want to avoid that.

**Comment by panchenkodv** [comment]
I offered a solution, but not nastavivat on it. While I will use what I have done, not yet fixed a bug or not this will be found another solution that will satisfy all.

**Comment by thyseus** [comment]
I just stumbled into _exact_ this issue and are voting for merging the changes in master !

**Comment by mikehaertl** [comment]
@thyseus As you probably have a use case can you explain a little why this is neccessary and what problem this exactly fixes? Maybe you can examplify a problematic process (including example URLs and where they come from).

**Comment by thyseus** [comment]
hey, @mikehaertl - thanks for the quick reply. our use case is the following:

we have a b2b marketplace that has this url scheme for categories:

`https://domain/rootcategory/subcategory/subsubcategory`

when hitting this url and, for example, want the german language, we want to redirect to:

`https://domain/de/rootcategory/subcategory/subsubcategory`

unfortunately because Yii createurl() _correctly_ (!) urlencodes the url, we get:

`https://domain/de/rootcategory%2fsubcategory%2fsubsubcategory`

which apache _correctly_ blocks away for security issues.

The solution will be to have an optional switch to (reencode) the url redirection.

**Comment by mikehaertl** [comment]
Hmm, ok, will have to check this later.

**Comment by mikehaertl** [comment]
Actually I still can't see how the URLs would be encoded. Your case is nothing special and exactly what this library was made for.

If you check our tests, you see that we check all redirect cases and *nowhere* is ever a urlencoded URL created. So how can this happen? And why doesn't it happen for everybody else using this extension?

**Comment by thyseus** [comment]
The 'problem' in my opinion is this line in the framework: 

https://github.com/yiisoft/yii2/blob/master/framework/web/UrlManager.php#L463

Since UrlManager extends from yii UrlManager this line is touched when redirecting.

The "special" case in my application (and in panchenkodv application) is to have a slash (/) character in an route parameter. We save the "full path" of the category in the database (it can have up to 7 levels depth !) for easier finding in the SQL query.

**Comment by mikehaertl** [comment]
Ok, but that's a different situation then. You basically have a URL parameter that contains `/` itself, right? Don't you have the same problem with URLs generated by Yii, too?

**Comment by mikehaertl** [comment]
BTW the line you referenced is only used if you don't use pretty URLs, so it's correct the way it is. In that case the Route must be url encoced in the `route=...` parameter. That's something different.

**Comment by mikehaertl** [comment]
Ok. Honest advice: You should not have `/` in URL parameters, as they *must* be encoded. So I'd say you should rather reconsider your approach. Like said before you also can't create these URLs with Yii (e.g. `Url::to()`) without the slashes being encoded. 

So our extension behaves correctly and I don't want to implement workarounds for questionable design decisions. In your case I'd split the dynamic URLs up and save 3 parameters in the DB (rootcategory, subcategory, subcategory). Then you can solve the issue by standard URL rules where you add each of them as separate parameter.

**Pull request closed without merging**
